import styles from "../../styles/global.module.scss";

export const metadata = {
  title: "Tecnica legaplan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={styles.main}>{children}</body>
    </html>
  );
}
