import styles from "../../styles/global.module.scss";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--fonte-principal",
});

export const metadata = {
  title: "Tecnica legaplan",
  description: "Generated by create next app",
  name: "viewport",
  content:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={roboto.className}>
      <body className={styles.main}>{children}</body>
    </html>
  );
}
